### ISSUE TITLE
Backend code cleanup

### ISSUE THREAD

**Issue by DaBernMon** [DBN16CO/Tactics#102]
Work on this should begin once Take Action and End Turn (the hopeful last commands for a Game) has been implemented. This should include:  
- Ensuring all "Internal Error" messages are of the same form (at least same capitalization for similarly-phrased parts)  
- The message format is consistent for all strings (Suggestion: "<String>".format(<vals>) - looks nice and clean)  
- All database fields should be changed to a most-appropriate name, for instance: x_pos -> x, hp_remaining -> hp, map_field -> map, etc.  
- All not-test backend files should receive an "A" (if possible) on codacy  
- Router does not handle all possible invalid inputs: missing 'Command', not being authenticated causes an unhanded error  
- While it won't be in production code, it may make further testing easier by reducing the horrible code duplication in the test files, and on that topic, the bad asserts (there is an assertFalse!)  

As new issues are found with the backend code, they should be added to the list, and the list should be updated as issues are fixed.

**Comment by akkowal2** [comment]
#138 and #141
