### ISSUE TITLE
Cannot Set Team in new Build

### ISSUE THREAD

**Issue by DaBernMon** [DBN16CO/Tactics#178]
After resetting the database it seems I can no longer set team (Clicking start ranked match).
  
I receive the error:  
NullReferenceException: Object reference not set to an instance of an object
GameController.Start () (at Assets/Scripts/GameController.cs:81)
  
Perhaps a match is required in order to set it in GameController's start?

**Comment by nrpriore** [comment]
This was a product of some test code - woops. fixed. SetTeam now loads the right scene
