### ISSUE TITLE
Front end no longer auto logs the user in using the token

### ISSUE THREAD

**Issue by akkowal2** [DBN16CO/Tactics#181]
Using the latest android apk, I created a user/logged in and then closed the app.  After opening the app again I am shown the login/register screen again.

**Comment by nrpriore** [comment]
lols I have it erasing the user key for testing and didn't switch it back before my push - will do so as part of next PR

**Comment by DaBernMon** [comment]
With the logout option, this is fixed.  Fixed in #202
