### ISSUE TITLE
Backend: Initiate Search for a Game

### ISSUE THREAD

**Issue by DaBernMon** [DBN16CO/Tactics#52]
This will implement the SG command in which the backend will receive JSON data detailing the units, perks, and leader that was chosen, this will:  
-Add that information to the database  
-Initiate a search for an opponent  
-Select a map for the two to play on  
-Respond with the map and opponent ID, to start the placing unit phase on the front  
  
EDIT:  
This process has been restructured, and will now take:  
- SG: Submit a team, which includes picking the leader, perks, and units (Done as of 10f28b3)
- FM: Find a match, called once the above team has been set, will find opponent and pick a map

**Comment by akkowal2** [comment]
Do we need to pass unit info in the json for searching for a game?  Won't there be a phase where they create the team (have units in the unit table with no Game ID) and then search should be able to find the units for their team in that table?

**Comment by DaBernMon** [comment]
This is the phase where they create the team.  Pick units,  perks, pick hero. Once that's done, they click find game. Which is this command

**Comment by akkowal2** [comment]
Okay, sounds good.

**Comment by DaBernMon** [comment]
I guess I may break it up into two commands. First one sends team info, second just says "okay find me a game now". Allows for a save team option if they're not ready to start a game

**Comment by akkowal2** [comment]
Yeah, that sounds good.  It allows for them to possibly create a default team setup in the future that they don't have to set for every game.

**Comment by DaBernMon** [comment]
As of pull #84, this is completed.
